export { default as ArrowIcon } from './arrow.svg'
export { default as StarIcon } from './star.svg'
export { default as BooksIcon } from './books.svg'
export { default as CoursesIcon } from './courses.svg'
export { default as ProductsIcon } from './products.svg'
export { default as ServicesIcon } from './services.svg'
export { default as Logo } from './logo.svg'
export { default as RateStarIcon } from './rateStar.svg'